### ISSUE TITLE
Update the `upsert` api to handle multiple columns as `unique index`

### ISSUE THREAD

**Issue by ozgrakkurt** [infinyon/sql-connector#75]
We want the api to look like this:

```yaml
apiVersion: 0.1.0
meta:
  version: 0.3.1
  name: json-sql-connector
  type: sql-sink
  topic: sql-topic
  create-topic: true
  secrets:
    - name: DATABASE_URL
sql:
  url: ${{ secrets.DATABASE_URL }}
transforms:
  - uses: infinyon/json-sql
    with:
      mapping:
        operation: "upsert"
        table: "topic_message"
        unique-columns: 
          - device_id
          - user_id
        map-columns:
          "device_id":
            json-key: "device.device_id"
            value:
              type: "int"
              default: "0"
              required: true
          "record":
            json-key: "$"
            value:
              type: "jsonb"
              required: true
```

@galibey maybe we can find a better name for `unique-columns`? since the combination of them should be unique and they don't need to be unique individually.
